### ISSUE TITLE
[bug] `@require/import 'xxx.css'` file within stylus file fail to build (v0.16.2+)

### ISSUE THREAD

**Issue by huafu** [quasarframework/quasar-cli#136]
### Software version

quasar-cli: 0.16.2+
OS: 10.13.4 (17E202)
Node: v9.11.1
NPM: 5.6.0

### What did you get as the error?
compile error, as if it'd try to stylus-compile bare css files

### What were you expecting?
to work as before `v0.16.2`, importing a css file within a stylus file should not try to compile it as a stylus file

### What steps did you take, to get the error?
```sh
yarn add flag-icon-css
```
in `src/css/app.styl`:
```stylus
@require '~flag-icon-css/css/flag-icon.css'
// ...
```
```sh
$ yarn add --dev quasar-cli@0.16.1
$ quasar dev
            ....everything ok.....
```
```sh
$ yarn add --dev quasar-cli@0.16.2 # also tried with .3 and .4
            ...lot of errors related to the css of required file...
```
I am not an expert in webpack but it sounds like **css** files required within a **stylus** file are not processed thru the `css-loader` anymore but with the `stylus-loader`

**Comment by rstoenescu** [comment]
Hi,

Due to the way webpack 4 & its css/stylus loaders work now, this is no longer possible (or possibly a bug in the loaders?). However, you're missing the point of quasar.conf > css array. It's there so you can specify the css/styl/scss/etc files of your app, in the order with which you want them included.

In current CLI version, you can add this:

```js
// quasar.conf
css: [
   // ......,
   '../../node_modules/flag-icon-css/css/flag-icon.css' 
]
```

Pushed a commit to simplify this. So in future CLI v0.16.5 you'll be able to simply say: `'~flag-icon-css/css/flag-icon.css'` (notice no "../../node_modules").

**Comment by huafu** [comment]
oh I missed that I could put it there, thanks!
