### ISSUE TITLE
quasar serve inconsistency

### ISSUE THREAD

**Issue by Boid-John** [quasarframework/quasar-cli#151]
The default history mode for the vue router in quasar is now 'history' instead of '#' 
However, the default mode for quasar serve is '#'

>  Tip: You can use "$ quasar serve" command to create a web server,
>       both for testing or production. Type "$ quasar serve -h" for
>       parameters. Also, an npm script (usually named "start") can
>       be added for deployment environments.
>       If you're using Vue Router "history" mode, don't forget to
>       specify the "--history" parameter: "$ quasar serve --history"

While the cli does throw a reminder about this, for new users it is more intuitive if things will automatically work together by default. Is there a reason that 'history' is not the default mode for quasar serve?

**Comment by rstoenescu** [comment]
Hi,

There's no default Vue Router mode. It's only what quasar.conf > build > vueRouterMode is set to.
The serve command can serve ANY www folder, not just Quasar app distributables. So it isn't connected to any config other than the parameters you are using it with.

Gonna do the other way around, and set vueRouterMode to "hash" in quasar-starter-kit instead.

Thanks for suggesting this.

**Comment by rstoenescu** [comment]
Can't really do that for multiple reasons:
1. You can do multiple type of builds, each with its own quasar.conf.
2. quasar.conf can be edited after a build

One solution would be to add a special file in the output folder (containing some info like vue router mode) and quasar serve can pick that up. But it feels kind of awkward to create a file just for quasar serve command, since not everybody will use quasar serve necessarily. So it seems like bloat.
