### ISSUE TITLE
`quasar dev` stuck when there's template render error

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar-cli#199]
### Software version

Operating System                Linux(4.15.0-38-generic) - linux/x64
NodeJs                          8.12.0

Global packages                 
  NPM                           6.4.1
  yarn                          1.10.1
  quasar-cli                    0.17.20
  vue-cli                       2.9.6
  cordova                       8.1.2 (cordova-lib@8.1.1)

Important local packages        
  quasar-cli                    0.17.20 (Quasar Framework CLI)
  quasar-framework              0.17.17 (Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase)
  quasar-extras                 2.0.8   (Quasar Framework fonts, icons and animations)
  vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### What did you get as the error?

UI: Working, in the latest working version.
Terminal: Black blank terminal, but if I scroll up I can see the cli stuck in building proccess.
 
### What were you expecting?
`quasar dev` should work without crashing even when there is template render error.

### What steps did you take, to get the error?
1. Run `quasar dev`
2. Cause template issue, for example: `<div v-if="os === 'Android"></div>` (the issue: I didn't close the string with single apos)

The worst part of it, I can't just kill the process with `ctrl+c` when the error occurred, I must kill the port 8089 to make this process stop, and the terminal should return to normal.

**Comment by rstoenescu** [comment]
Hi,

This is not handled by Quasar. It's handled entirely by vue-loader + webpack. It's one of the reasons why you might want to enable linting on your project, to catch this before it happens.

If you want this fixed, I suggest you open up a ticket on vue-loader's repository.

-Razvan

**Comment by MatanYed** [comment]
Thanks! I sent issue to Vue team.

**Comment by CheyenneForbes** [comment]
I'm not sure if this is the same issue but I'm not seeing any errors when theres a template error

```
 Dev mode.......... spa
 Pkg quasar........ v1.0.0-beta.10
 Pkg @quasar/app... v1.0.0-beta.11
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +5ms
 app:webpack Extending SPA Webpack config +942ms
 app:generator Generating Webpack entry point +25ms
 app:dev-server Booting up... +10ms


  SPA █████████████████████████ [100%] in ~15s
```

**Comment by zainulabidin302** [comment]
There should a way for `verbose output` in dev mode in which standard output shows output from other modules.

**Comment by rstoenescu** [comment]
@zainulabidin302 like I previously mentioned, this is entirely handled by vue-loader and webpack, so those are the places where you should push for this.

**Comment by xeor** [comment]
Anyone have a reference to another issue? This problem just ate a couple of hours of my day as well. The dev window turned blank, no errors, no nothing, and whatever I did gave no results. The reason being I brainfarted and defined a prop with a `-` in the name...

**Comment by bpkennedy** [comment]
@rstoenescu , I hear you when you say that the issue with failed compilation is in vue-loader + webpack.  However, in a Vue-CLI generated project when compilation failure happens there are errors logged in terminal that point to the issue (file, line, char, etc...).

Listing those errors in terminal is not their problem, but Quasars.  Is there a debug/verbose mode or some other conditional flag that we can have added to display this detail for us instead of the compile just sitting there stuck with no information as to why?

This has already caused me at least 10 minutes of shrugging and randomly commenting out/back in code blocks trying to figure out what is making it fail.  This is the first time I've used Quasar in a project, and I'm about an hour in.  This is kind of frustrating.

Update:  After futzing around, it seems the compile is non-deterministic.  It will compile correctly for three or four iterations of `quasar dev` and then the same code might hang at 0% compile on the fourth or fifth run.  I don't understand why.  I've added three files since the quaser-cli generated a project, and pored over them but there doesn't seem to be anything wrong.

I'm not sure what code to show you, as it's a pretty vanilla generated project, new file-wise.  Here is the public repo if you cared to try building on your own to repro what I am seeing.  Try running quasar dev about 10 times and you'll see the issue.  https://github.com/bpkennedy/harmony-church-chat
