### ISSUE TITLE
[Request] Add option for CORS

### ISSUE THREAD

**Issue by joep** [quasarframework/quasar-cli#203]
Currently, I am developing a quasar app that interacts with couchdb. I am running into issues regarding cross origin requests to the db being blocked by the browser since they go to a different port. It would be nice if there were an option to quasar-serve to use cors middleware (https://github.com/expressjs/cors), maybe set up by the devServer options in quasar.conf.js?

**Comment by rstoenescu** [comment]
yarn/npm install cors then:

```
devServer: {
   before (app) {
      const cors = require('cors')
      app.use(cors())
   }
}
```

**Comment by rstoenescu** [comment]
More info on devServer Webpack options: https://webpack.js.org/configuration/dev-server/#devserver-before

**Comment by joep** [comment]
Thanks very much for the info. I just started with quasar (which is awesome) and didn't realize those options are dropped directly to the webpack devserver although it makes perfect sense they are.

**Comment by dariosalviwork** [comment]
hello, I am in the same situation, testing an app with `cordova dev`, but it can't call the API because it's on another server. I have tried adding cors, as you suggested but it says it can't find it.
Where should I install it? In the src-cordova project? In the root project?
Is there any simpler trick I could use?
Thanks a lot.

**Comment by rstoenescu** [comment]
@dariosalviwork See my comment from top. It's quasar.conf.js -- and I highly suggest you visit it's doc page on Quasar website.

**Comment by dariosalviwork** [comment]
thanks Razvan, I have had a look at the Quasar docs and also Webpack's devserver.
You suggest to add 

```
devServer: {
   before (app) {
      const cors = require('cors')
      app.use(cors())
   }
}
```

into quasar.conf.js, which I did, but quasar-cli complains because it can't find the module `cors`. Where do you suggest to install it? in the project's folder? in `src-cordova`? globally? or where `cordova-cli` is located?

thanks for your precious help.

**Comment by rstoenescu** [comment]
@dariosalviwork in the root of your project: `yarn add --dev cors`.
