### ISSUE TITLE
Totally get rid of ESLint

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar-cli#86]
ESLint is the worst thing ever done to Quasar. I don't really know why developer decided this and it has no clear documentation how to get rid of this. I spent my half time fixing things for ESLint. I dont like it and I want to completely wipe it out from my project. Any help is really appreciated.

**Comment by mstaack** [comment]
hey @george-kar !

actually eslint helps teams & code to stay consistent. otherwise you will have difficult to read diffs etc..
check https://medium.com/the-node-js-collection/why-and-how-to-use-eslint-in-your-project-742d0bc61ed7


you have an `.eslintignore` file in your root folder.  Add `/src`  does this help?

Cheers Max

**Comment by rstoenescu** [comment]
Hi, Things to note:

1. The starter kit asks you if you want linting or not. So opt out.
2. If you opted for ESLint but want to disable it, just edit /quasar.conf.js > build > extendWebpack and remove it:
```js
cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules|quasar)/
        })
```
...and you're done.

If you are using pre v0.15, then edit the /build/ files and remove same thing from there.

**Comment by george-kar** [comment]
@mstaack is hard to configure tabs and spaces when you have a huge project and you just copy paste code from a project to a new quasar project. I am using VS Code and it was almost impossible to setup and fix indents in mixed files like vue (which contain html and js code).

@rstoenescu well, you are right, it asked me but I accidentally pressed Y. Maybe it was the default option.

I have managed to find all options that produce spacing and tab errors. Instead of totally disabling ESLint I added these rules inside .eslintrc.js > Rules

'indent': ['off', 4],
'no-mixed-spaces-and-tabs': ['off', 'smart-tabs'],
'no-spaced-func': 0,
'func-call-spacing': 0,
'space-before-function-paren': 0

**Comment by a47ae** [comment]
@george-kar That is exactly the reason why you should use ESLint from the start, to avoid a mess from different code styles.

ESLint has a fix ability for most stylistic issues, which does automatically fix you code, you may want to try this. See the `--fix` option https://eslint.org/docs/user-guide/command-line-interface

**Comment by george-kar** [comment]
@a47ae I would probably configure it properly in future, but right now I have a deadline and I need to focus to serious things, not styling my spaces, my tabs and my lines. I have dozen of files to move from another project to a new Quasar project and all these styling (minor) issues are wasting my time.

**Comment by a47ae** [comment]
Fair point, so best luck with you project, if you run in some problems while migrating just ask on Discord! :)

**Comment by Akaryatrh** [comment]
>ESLint has a fix ability for most stylistic issues, which does automatically fix you code, you may want to try this. See the --fix option https://eslint.org/docs/user-guide/command-line-interface

@a47ae how do you add the `--fix` option in quasar environment?

**Comment by rstoenescu** [comment]
@Akaryatrh just run `$ eslint --fix <folders...>` https://eslint.org/docs/user-guide/command-line-interface

**Comment by Akaryatrh** [comment]
@rstoenescu sorry, I might have misexpressed myself. I meant: how do you add the `--fix` option while running `quasar dev` script? (I don't want to run eslint in a supplemental tab BTW)

**Comment by Hugoberry** [comment]
make sure you have this option added to your `quasar.conf.js` 
```
      extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules|quasar)/,
          options: {
            fix: true
          }
        })
      }
```

**Comment by Akaryatrh** [comment]
Omg It was so simple, I feel stupid… Thx a lot @Hugoberry!

**Comment by HankBrown** [comment]
Wildly distracting. Is enabled in showcase and many learning tools.
No fix is  "simple" the day you start. The one above did not fly for me.
I found **add "/src" to "./eslinignore"** in the main folder did the trick.

Great product thank you.

**Comment by turigeza** [comment]
I think I am going to end up disabling it as well on the long run. I find for me it is better for the editor to lint instead of blocking quasar dev. It took me 1.5 day to get Atom to lint the Vue files . : ) 

It also worth mentioning the --fix will not fix everything even some very basic easy to fix stylistic stuff like { something: 3} you will have to change it yourself to { something: 3 }.

This page helped me a lot ! Thank you!

**Comment by aislanmaia** [comment]
I endorse this. Eslint sometimes makes me wasting my time. Look, I'm trying to get `vuex` in the hot module like described [here](https://v1.quasar-framework.org/quasar-cli/cli-documentation/vuex-store#Introduction) and now my linter blocks the `quasar dev` forcing me to learn Eslint things because it cant to know about the variables `require` and `module` in the code, wasting my time when it should just warning me the problem.

And that is just a solo project with one developer. Eslint makes some assumptions about my code style that irritates me, because I need to go through the Eslint docs to learn how to change the defaults.

I choose to add Eslint when initializing the project because I thought it was a smart tool, but it is really dumb blocking the way because minor issues.

**Comment by beedrill** [comment]
I completely agree, Eslint hugely slowed done debugging, everytime I need to try things out, I have to fix Eslint's 'defined but not used' stupid error.
